- type: startingGear
  id: ChiefCCAdmemeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNavyGold
    back: ClothingModsuitExperimental
    shoes: ClothingShoesChameleonNoSlips
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    outerClothing: ClothingOuterDogi
    id: AdminPDA
    ears: ClothingHeadsetChronolegioneer
    head: ClothingHeadHatCentcomcap
    neck: ClothingNeckCloakCentcom
    belt: ClothingBeltSheathFilledNavyOfficer
  storage:
    back:
    # Survival
    - BoxSurvivalSlotsEngineering
    # Tools
    - SonicScrewdriver
    - RCDChrono
    - RPDRecharging
    - NetworkConfigurator
    - WelderExperimental
    - GasAnalyzer
    - HolofanProjectorEmpty
    - trayScanner
    - AccessConfiguratorUniversal
    - DoorRemoteAll
    # Science
    - AnomalyLocatorEmpty
    - WeaponPistolCHIMP
    - AnomalyScanner
    - ChronoTeleporter
    # Security
    - Wonderprod
    - WeaponDisablerSMG
    - WeaponPulseRifle
    - Handcuffs
    - Handcuffs
    - Handcuffs
    # Medical
    - DefibrillatorCompact
    - MedkitCombatStasiziumFilled
    - MedkitCombatFilled
    - OmnimedTool
    - ClothingMaskSterile
    - ClothingHandsGlovesNitrile
    # Implants
    - MindShieldImplanter
    - TrackingImplanter
    - BluespaceLifelineImplanter
    - BlinkImplanter
    - ShiftImplanter
    - StopTimeImplanter
    - VaporizeImplanter
    - CentcommFreedomImplanter
    # Misc
    - LightReplacerLEDAdmeme
    - PortableRecharger
    - PowerCellAntiqueProto
    - PowerCellAntiqueProto
    - PowerCellAntiqueProto
    - PowerCellAntiqueProto
    - PowerCellAntiqueProto
    # Martial Arts
    - SleepingCarpScroll
    - ClothingHandsGlovesKravMaga
    - BSOManual
