- type: latheRecipePack
  id: ServiceWeapons
  recipes:
  - WeaponLaserSvalinn

- type: latheRecipePack
  id: ServicePartsStatic
  recipes:
  - MicroManipulatorStockPart
  - MatterBinStockPart
  - CapacitorStockPart
  - CableStack
